### PR TITLE
Enhance status check label for promotions

### PR DESCRIPTION
**Pull request by michelangelomo**
This PR introduces a change for labels applied to status checks related to promotions, actually a generic one is used.

### CODE REVIEW

**Comment by michelangelomo** [comment]
hi @bradrydzewski, we would like to use this change asap, could you drop a review? :pray:

**Comment by tphoney** [comment]
I had a look at the change, and this seems to be additive so it shouldnt affect any existing functionality.  I will defer to Brad, as i have not looked at the lifecycle of statuses in depth

**Comment by aleinside** [comment]
hi @tphoney, any feedback from @bradrydzewski? 🙏

**Comment by michelangelomo** [comment]
@tphoney @bradrydzewski bump

**Comment by bradrydzewski** [comment]
The `deploy` value is freeform and may contain special characters, spaces, etc.  Do we know that all providers (github, gitlab, gitea, bitbucket, stash, azure) support freeform text and no character restrictions?  If yes, then we are good to merge.  If no, I would recommend taking the slug value (using the existing slug library that we already import).

```diff
import (
	"fmt"

	"github.com/drone/drone/core"
	"github.com/drone/go-scm/scm"

+	github.com/gosimple/slug
)
```

```diff
	case core.EventPromote:
-		return fmt.Sprintf("%s/promote/%s", name, deployTo)
+		return fmt.Sprintf("%s/promote/%s", name, slug.Make(deployTo))
```

**Comment by michelangelomo** [comment]
> The deploy value is freeform and may contain special characters, spaces, etc. @tphoney do we know that all providers (github, gitlab, gitea, bitbucket, stash, azure) support freeform text and no character restrictions? If yes, then we are good to merge. If no, I would recommend taking the slug value (using the existing slug library that we already import).

hey @bradrydzewski, I think your suggestion is reasonable even if may there are no special character, better safe than sorry :smile:

**Comment by SharpEdgeMarshall** [comment]
Any update on this?

**Review by d1wilko — APPROVED** [review]
LGTM - thanks for the change @michelangelomo - apologies for the delay

**Pull request merged**
