### PR TITLE
support time zone

### PR DESCRIPTION
**Pull request by zc2638**
When I set other time zone it always doesn't take effect, tzdata is missing in alpine image.

### CODE REVIEW

**Comment by tphoney** [comment]
Do you set the timezone after with an environment variable, like this ?

```
-e TZ=Europe/London
```

**Comment by zc2638** [comment]
> Do you set the timezone after with an environment variable, like this ?
> 
> ```
> -e TZ=Europe/London
> ```

Yes.

**Comment by tphoney** [comment]
tested this locally, works well. 

Many thanks @zc2638  🥂

**Comment by tphoney** [comment]
i added docs as well https://github.com/drone/docs/pull/577

**Comment by TankNee** [comment]
I meet the same issue in latest linux amd64 docker image, I have set the TZ environment variable in my docker-compose.yml file and it doesn't work correctly.
image
The following is drone page time and my system time.
image

**Pull request merged**
